version: '3.0'
services:
  git:
    image: ghcr.io/claudio4/git-http-backend-container:master
    restart: unless-stopped
    user: '1001:1001' # change this ass needed.
    volumes:
      - "/path/to/host/gitdir:/git"
      - "/path/to/your/auth/file:/etc/nginx/htpasswd:ro" # this mount is reads-only.
